schema_name: excelutil

spring:   
  application:
    name: excelutil 
  docker:
    compose:
      enabled: false
  sql:
    init:
      platform: h2
      continue-on-error: false
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      mode: always 
      schema-locations: db\schema-h2.sql
      data-locations: db\import_*_users.sql 
  datasource: 
     url: jdbc:h2:mem:${schema_name};DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;NON_KEYWORDS=USER;INIT=CREATE SCHEMA IF NOT EXISTS ${schema_name}\;set schema=${schema_name}
     driver-class-name: org.h2.Driver
     username: ${DATASOURCE_USERNAME}
     password: ${DATASOURCE_PASSWORD}  
     hikari:
       maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:2}
  jpa:
    show-sql: false
    defer-datasource-initialization: false 
    open-in-view: false 
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: 
        default_schema: ${schema_name}
        format_sql: false
        physical_naming_strategy: com.sirenanalytics.siren_survey.config.SnakeCaseNamingStrategy
        globally_quoted_identifiers: true
    
logging:
  level:
    org.hibernate.type: INFO
    org.hibernate.SQL: debug